### PR TITLE
GPII-4176: escaping console.log in JS wrapper for JSON content.

### PR DESCRIPTION
**Pull request by jobara**
https://issues.gpii.net/browse/GPII-4176

### CODE REVIEW

**Comment by jobara** [comment]
@the-t-in-rtf would you be able to review this PR?

**Comment by the-t-in-rtf** [comment]
@jobara, good catch.  I'd like to pair this with the [long-standing open pull to add console.log to eslint-config-fluid](https://github.com/fluid-project/eslint-config-fluid/pull/6), and to review/merge this after that one, so that we're also testing your small change here with the updated defaults.

cc: @amb26

**Comment by jobara** [comment]
@the-t-in-rtf I've updated the PR to use eslint-config-fluid v1.4.0 and fixed issues with `console.log` as well.

**Comment by jobara** [comment]
@the-t-in-rtf I'm closing this PR now that https://github.com/GPII/gpii-grunt-lint-all/commit/89c9c99349d9141d86b66765322815efea92a7e6 has resolved this issue. Can you please publish a new release of this package though, as the places that use eslint-config-fluid v1.4.0 with this will fail due to the bug in earlier versions.

**Comment by the-t-in-rtf** [comment]
Sorry, @jobara, totally missed this.  There is a dev release with the changes here:

1.0.6-dev.20191126T114627Z.377dbc8.GPII-4246

We are working on one more change (removing JSONlint in favour of our own custom task), I plan to cut a full release once that's done.

**Comment by jobara** [comment]
@the-t-in-rtf sounds good and thanks for the dev release.

**Comment by the-t-in-rtf** [comment]
@jobara, I finished the other work, the full 1.0.6 release is out now.

**Comment by jobara** [comment]
excellent, thanks :)

**Pull request closed without merging**
